---
title: "All 25 Cities Italy"
author: "Laura Albrecht"
date: "8/6/2020"
output:
  html_document: default
  pdf_document: default
---

Create GAM models for all 25 cities in Italy as well as all of Italy combined.

```{r echo = FALSE, message = FALSE, warning = FALSE}
source("ReadAllData1.R")
library(mgcv)
#all of italy
italy_25gam <- gam(log(rt1)~ 
                    s(home, k = 5)+s(pm25, k = 5)+s(med_temp, med_hum, k=5), data = italy_25, family = gaussian)

plot(italy_25gam, scale=0,se=2, shade=TRUE,pages=1, scheme = 2,main = "25 Cities in Italy")
summary(italy_25gam)
gam.check(italy_25gam)

#all of italy including city
#italy_25f <- italy_25
#italy_25f$city_name <- as.factor(italy_25$city_name)

#italy_25gam <- gam(log(rt1)~ 
#                    s(home, k = 5)+s(pm25, k = 5)+s(med_temp, k = 5)+s(med_hum, k = 5)+city_name, data = italy_25f, family = gaussian)

#plot(italy_25gam,scale=0,se=2, shade=TRUE,pages=1, scheme = 2,main = "25 Cities in Italy")
#summary(italy_25gam)


```

```{r message = FALSE, warning = FALSE, echo = FALSE}
library(mgcv)
#loop through and save gams
for(city in city_names){
  assign( paste(city,"_gam", sep = ""), gam(log(rt1)~ 
                    s(home)+s(pm25, k = 5)+s(med_temp, med_hum, k = 5), data = italy_25[italy_25$city_name == city,], family = gaussian))}

#loop through and plot gams
for(city in city_names){
  plot(get(paste(city, "_gam", sep = "")),scale=0,se=2, shade=TRUE,pages=1, scheme = 2, main = city)
}

#for(city in city_names){
#  summary(get(paste(city, "_gam", sep = "")))
#}
 # summary(temp.gamM1)
 # gam.check(temp.gamM1)


```




Making a GAM for all cities combined, excluding each one:
```{r}
source("ReadAllData1.R")
library(mgcv)
for (city in city_names) {
  new_data = subset(italy_25, city_name!=city)
  assign( paste(city,"_exclude_gam", sep = ""), gam(log(rt1)~ 
                    s(home)+s(pm25, k = 5)+s(med_temp, med_hum, k = 5), data = new_data, family = gaussian))

  plot(get(paste(city, "_exclude_gam", sep = "")),scale=0,se=2, shade=TRUE,pages=1, scheme = 2, main = city)

}


```

Using that GAM to predict the excluded city's outcome:
```{r}

source("ReadAllData1.R")
library(mgcv)
library(ggplot2)


for (city in city_names) {
  city_data = subset(italy_25, city_name==city)
  city_gam <- get(paste(city, "_exclude_gam", sep = ""))
  pred_cases <- predict(city_gam,city_data)
  
  plot((pred_cases)-log(city_data$rt1), scale=0,se=2, shade=TRUE,pages=1, scheme = 2, main = city)


}



```










